// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "alertDanger": "rgba(220, 53, 69, 1)",
 "alertDangerBackground": "rgba(248, 224, 224, 1)",
 "alertWarning": "rgba(255, 193, 7, 1)",
 "alertWarningBackground": "rgba(252, 248, 227, 1)",
 "alertSuccess": "rgba(40, 167, 69, 1)",
 "alertSuccessBackground": "rgba(223, 240, 216, 1)",
 "alertInfo": "rgba(0, 102, 221, 1)",
 "alertInfoBackground": "rgba(184, 208, 236, 1)",
 "primarySelected": "rgba(51, 51, 51, 1)",
 "primaryActive": "rgba(72, 76, 81, 1)",
 "primaryHover": "rgba(84, 89, 94, 1)",
 "primaryInactive": "rgba(108, 117, 125, 1)",
 "brandLeadRoi": "rgba(222, 140, 8, 1)",
 "brandLeadGen": "rgba(0, 96, 156, 1)",
 "brandLeadNav": "rgba(76, 157, 47, 1)",
 "graysGray5": "rgba(242, 242, 242, 1)",
 "graysGray4": "rgba(224, 224, 224, 1)",
 "graysGray3": "rgba(189, 189, 189, 1)",
 "graysGray2": "rgba(130, 130, 130, 1)",
 "graysGray1": "rgba(79, 79, 79, 1)",
 "white": "rgba(255, 255, 255, 1)",
 "black": "rgba(34, 34, 34, 1)"
}

module.exports = colors;